//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoG.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int MoveId { get; set; }
        public System.Guid GameId { get; set; }
        public int Sequence { get; set; }
        public string Position { get; set; }
        public string Captured { get; set; }
        public bool IsBlack { get; set; }
        public byte MoveType { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
