//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoG.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingId { get; set; }
        public string ActiveMessage { get; set; }
    }
}
