//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoG.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Moves = new HashSet<Move>();
        }
    
        public System.Guid GameId { get; set; }
        public bool BlacksTurn { get; set; }
        public string BlackStones { get; set; }
        public string WhiteStones { get; set; }
        public System.DateTimeOffset Started { get; set; }
        public byte Size { get; set; }
        public byte Status { get; set; }
        public System.DateTimeOffset LastMove { get; set; }
        public string Player1Name { get; set; }
        public string Player2Name { get; set; }
        public byte Player1Type { get; set; }
        public byte Player2Type { get; set; }
        public decimal Player1Score { get; set; }
        public decimal Player2Score { get; set; }
        public byte Player1Level { get; set; }
        public byte Player2Level { get; set; }
        public decimal WinMargin { get; set; }
    
        public virtual ICollection<Move> Moves { get; set; }
    }
}
