//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoG.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public string Level { get; set; }
        public string Context { get; set; }
        public string ExceptionType { get; set; }
        public string Exception { get; set; }
        public Nullable<System.Guid> GameId { get; set; }
    }
}
